FROM alpine:3.9.3

USER root
WORKDIR /root

RUN apk add p7zip git tzdata openssh-client
RUN cp /usr/share/zoneinfo/Asia/Seoul /etc/localtime; \
echo "Asia/Seoul" > /etc/timezone; \
git config --global user.email "whya5448@gmail.com"; \
git config --global user.name "작은게이"

RUN apk del tzdata

ADD ./ssh/known_hosts /root/.ssh/

ENV LC_ALL ko_KR.UTF-8
ENV ESO_SERVER_DIR /root/eso_server

# From release -server
ADD launch-linux-x64.7z . 
RUN 7z x launch-linux-x64.7z; \
rm launch-linux-x64.7z; \
chmod 700 ./bin/*

WORKDIR /root/bin
CMD /root/bin/launch